### ISSUE TITLE
Sends too much too discord

### ISSUE THREAD

**Issue by xetsubou** [LakeYS/Dishorde#105]
this worked fine at first but it sends this long line nowadays for some reason, was doing the same thing on a18.4

[discord bot issue video 2020-07-14 10-11-26.zip](https://github.com/LakeYS/7DTD-Discord/files/4919296/discord.bot.issue.video.2020-07-14.10-11-26.zip)

**Comment by LakeYS** [comment]
Closing as stale for now.
