### ISSUE TITLE
1.7.2/1.7.3 bot disconnects after period of time requiring restarts.

### ISSUE THREAD

**Issue by Flukester69** [LakeYS/Dishorde#116]
Bot does not stay connected. The server pauses if nobody is on. I believe after certain amount of time, your bot auto-disconnects.
It would be nice if it would check periodically so that the bot doesn't have to be restarted continuously.

**Comment by LakeYS** [comment]
Will look into this.

For the release version number, you can now re-download to receive the correct version number.

**Comment by Flukester69** [comment]
Yes, I had to remove my original download of 1.7.2 and extract and use 1.7.3 to resolve the issue.

**Comment by LakeYS** [comment]
Closing as stale for now.
