### ISSUE TITLE
[v2.0.0-rc1] hide-prefix not working

### ISSUE THREAD

**Issue by trevorjd** [LakeYS/Dishorde#120]
I killed Dishorde, enabled "hide-prefix": true then fired it back up. Slash commands like visit, group and gamble are still being echoed to Discord.

**Comment by LakeYS** [comment]
Will look into this.

**Comment by LakeYS** [comment]
Fixed in 324cf6d.

The fix is included in 2.0.0-rc2: https://github.com/LakeYS/Dishorde/issues/119#issuecomment-1003171264
