### ISSUE TITLE
REQ - Use nicknames rather than Discord base names when sending messages to game

### ISSUE THREAD

**Issue by trevorjd** [LakeYS/Dishorde#123]
Noticed this evening that a message sent from Discord to game came through with their base discord handle (text portion of username#1234) rather than their nickname (which is the same as their steam name / IGN). It would be great if Dishorde can pick up the nickname instead (or at least have that as a configurable option).

**Comment by LakeYS** [comment]
Done! fd2d76e

**Comment by trevorjd** [comment]
Now _that's_ service!
