### ISSUE TITLE
Bot ignoring

### ISSUE THREAD

**Issue by xTlosx** [LakeYS/Dishorde#128]
Any chance the bot can allow other bots to trigger it's commands?  

Been fiddling for a bit, but would like my button bot to send the 7d!players command and have it respond...  just 1 less thing to type ig.  
True / false option maybe?

Thank you 
C> Ice cream for anyone who reads this :)

**Comment by LakeYS** [comment]
This is done as a safety precaution to prevent bots behaving unexpectedly (such as getting stuck in a "feedback loop") by talking to each other. For this reason, I would be hesitant to make a config option.

However, for your purposes, modifying the code will likely be pretty simple. You can [delete or comment out this check in the parseDiscordCommand function](https://github.com/LakeYS/Dishorde/blob/master/index.js#L392) to accomplish this. This should allow Dishorde to accept input from other bots.

**Comment by LakeYS** [comment]
Closing for now. Feel free to reply back with any further questions, or reach out on [Discord](https://discord.gg/s3vCQba).
