### ISSUE TITLE
Time and Version not working.

### ISSUE THREAD

**Issue by d0zzer2** [LakeYS/Dishorde#129]
Chat messages are being relayed both ways and players returns the number of players online but the time and version commands aren't working. If it telnet in and try gettime and version they both work as they should so I'm not sure what's happening.

We are using the Darkness Falls mod if that matters.

**Comment by LakeYS** [comment]
Mod compatibility is unfortunately spotty, so there is a good chance the mod is related. This issue can be looked at for a fix in the future.

Can you confirm that your version of the bot is the latest, 2.0.1? Could you also check if anything shows up in the game server's console when someone types the time and/or version commands? The goal here is to narrow down if the commands from the bot are ever going through at all.

**Comment by LakeYS** [comment]
Closing as stale for now.
