### ISSUE TITLE
7dtd!time should display a different message when it is currently a horde night

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Dishorde#77]
Currently says "7 days to next horde" on the night of a horde ("6 days" when past midnight in-game)

Proposed fix, **untested**, based on contributed code by @cjakesmith: (In addition to adding this, add the option `
```
function handleTime(line, msg) {
  const messageValues = line.split(",");
  const day = parseInt(messageValues[0].replace("Day ", ""));
  const hour = parseInt(messageValues[1].split(":")[0]);
  let dayHorde = day % parseInt(config.hordefrequency);
  let hordeMsg = "";

  if (dayHorde === 0 && hour < 22) {
    hordeMsg = "The horde comes tonight!";
  } else if (dayHorde === 0 && hour >= 22 || dayHorde === 6 && hour < 22) {
    hordeMsg = "The horde is rampaging now!";
  } else if (dayHorde !== 0) {
    dayHorde = parseInt(config.hordefrequency) - dayHorde;
    hordeMsg = `${dayHorde} day${dayHorde === 1 ? "" : "s"} to next horde.`;
  }

  msg.channel.send(hordeMsg);
}
```

**OLD user-contributed code:**
```
function handleTime(line, msg) {
    const messageValues = line.split(',');
    const day = parseInt(messageValues[0].replace('Day ', ''));
    const hour = parseInt(messageValues[1].split(':')[0]);
    let dayHorde = day % 7;
    let resp = ``;

    if (dayHorde === 0 && hour < 22) {
        resp = `The horde comes tonight!`;
    } else if (dayHorde === 0 && hour >= 22 || dayHorde === 6 && hour < 22) {
        resp = `The horde is rampaging now!`;
    } else if (dayHorde !== 0) {
        dayHorde = 7 - dayHorde;
        resp = `${dayHorde} day${dayHorde === 1 ? `` : `s`} to next horde.`;
    }

    msg.channel.send(`${line}\n${resp}`);
    Telnet.exec(`say "${line} ${resp}"`);
}
```

**Comment by cjakesmith** [comment]
The previous user contributed code works, but if you want to add the ability to easily change the Horde night frequency you can use this:

`function handleTime(line, msg) {
  const messageValues = line.split(',');
  const day = parseInt(messageValues[0].replace('Day ', ''));
  const hour = parseInt(messageValues[1].split(':')[0]);
  let dayHorde = day % parseInt(config.hordefrequency);
  let resp = ``;

  if (dayHorde === 0 && hour < 22) {
      resp = `The horde comes tonight!`;
  } else if (dayHorde === 0 && hour >= 22 || dayHorde === 6 && hour < 22) {
      resp = `The horde is rampaging now!`;
  } else if (dayHorde !== 0) {
      dayHorde = parseInt(config.hordefrequency) - dayHorde;
      resp = `${dayHorde} day${dayHorde === 1 ? `` : `s`} to next horde.`;
  }`

And add this definition to config.json
`"hordefrequency": "7"`

**Comment by LakeYS** [comment]
Done in 7991e7a
