### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Dishorde#85]
The bot currently does not have any easy way to be localized for different languages. Fixing this would allow the bot to reach more people.

A service like CrowdIn (https://crowdin.com/) could be used to translate the bot, but the implementation process may be difficult.

**If you are interested in helping with translation, please [join this discord](https://discord.gg/s3vCQba) and subscribe to this issue. Updates will be posted soon.**

**Comment by thomasbonsirven** [comment]
Hello,

I ready for translate into French.

**Comment by LakeYS** [comment]
Closing out feature requests to keep this tracker to bugs-only. This does not mean that this feature is a "won't-add". Further discussion is being moved to the [Discord](https://discord.gg/s3vCQba).
